HF_EMAIL="trevormcgirr@gmail.com"
HF_TOKEN="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"
OPENAI_API_KEY="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"
PINECONE_API_KEY="06806c7f-fa85-421c-b0b5-8c67fd0d4916"
PINECONE_INDEX_NAME="gcp-starter"